sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t fciortan/docker-react .

script:
  - docker run -e CI=true fciortan/docker-react npm run test

deploy:
  provider: elastibeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-798859907642"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
